development:
  location: http://localhost:3000/api/v1
  languages:
    core:
      - en
      - es
    web:
      - en
      - es

test:
  location: http://localhost:3000/api/v1
  languages:
    core:
      - en
      - es
    web:
      - en
      - es

production:
  location: https://redeemy-api.herokuapp.com/api/v1
  languages:
    core:
      - en
      - es
    web:
      - en
      - es
